version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
           
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command:
           Invoke-webRequest https://raw.githubusercontent.com/tata2022/Vps/main/sh
      - run: .\gpu.ps1